services:
  - type: web
    name: project-meghana
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://vidyasirimane_db_user:123456@cluster0.hdzvoym.mongodb.net/krishi_connect?retryWrites=true&w=majority
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: /api
